// <auto-generated />
using System;
using Budjoni.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budjoni.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200922121307_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budjoni.DAL.Models.BojaModela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdModela")
                        .HasColumnType("int");

                    b.Property<byte[]>("SlikaByteArray")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdModela");

                    b.ToTable("BojaModela");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.BrojBojeModela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdBojeModela")
                        .HasColumnType("int");

                    b.Property<string>("KolicinaNaStanju")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Velicina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdBojeModela");

                    b.ToTable("BrojBojeModela");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.ModelObuce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivModela")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModeliObuce");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.BojaModela", b =>
                {
                    b.HasOne("Budjoni.DAL.Models.ModelObuce", "ModelObuce")
                        .WithMany("BojeModela")
                        .HasForeignKey("IdModela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Budjoni.DAL.Models.BrojBojeModela", b =>
                {
                    b.HasOne("Budjoni.DAL.Models.BojaModela", "BojaModela")
                        .WithMany("BrojeviBojeModela")
                        .HasForeignKey("IdBojeModela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
