// <auto-generated />
using System;
using Budjoni.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budjoni.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budjoni.DAL.Models.DetaljiNarudzbine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdModelaObuce")
                        .HasColumnType("int");

                    b.Property<int>("IdNarudzbine")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdModelaObuce");

                    b.HasIndex("IdNarudzbine");

                    b.ToTable("DetaljiNarudzbine");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.ModelObuce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivModela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SlikaByteArray")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ModeliObuce");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.Narudzbina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresaZaPrikaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMesta")
                        .HasColumnType("int");

                    b.Property<int>("IdNalogaSaKogSeSalje")
                        .HasColumnType("int");

                    b.Property<int>("IdUlice")
                        .HasColumnType("int");

                    b.Property<int>("IdVrsteRobe")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KucniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NalogSaKogSeSalje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Otkup")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("UlazIliStan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Naruzbine");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.VelicinaModela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdModelaObuce")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaNaStanju")
                        .HasColumnType("int");

                    b.Property<string>("Velicina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdModelaObuce");

                    b.ToTable("VelicinaModela");
                });

            modelBuilder.Entity("Budjoni.DAL.Models.DetaljiNarudzbine", b =>
                {
                    b.HasOne("Budjoni.DAL.Models.ModelObuce", "ModelObuce")
                        .WithMany()
                        .HasForeignKey("IdModelaObuce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budjoni.DAL.Models.Narudzbina", "Narudzbina")
                        .WithMany("DetaljiNarudzbine")
                        .HasForeignKey("IdNarudzbine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Budjoni.DAL.Models.VelicinaModela", b =>
                {
                    b.HasOne("Budjoni.DAL.Models.ModelObuce", "ModelObuce")
                        .WithMany("VelicineModela")
                        .HasForeignKey("IdModelaObuce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
